package Route.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;

public class forward_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_bm7pr7_a(editorContext, node);
  }
  private EditorCell createCollection_bm7pr7_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_bm7pr7_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_bm7pr7_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_bm7pr7_b0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_bm7pr7_c0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_bm7pr7_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Forward Command:=>");
    editorCell.setCellId("Constant_bm7pr7_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_bm7pr7_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Distance:");
    editorCell.setCellId("Constant_bm7pr7_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_bm7pr7_c0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("distance");
    provider.setNoTargetText("<no distance>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_distance");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
    } else
    return editorCell;
  }
}
