package forwardCommand.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_command = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_forward = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ourcanvas = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_turn = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_command;
      case 1:
        return props_forward;
      case 2:
        return props_ourcanvas;
      case 3:
        return props_turn;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
